version: "3"
services:
  rabbitmq:
    container_name: maild-rabbitmq
    image: "rabbitmq:3-alpine"
    ports:
    - "5672:5672"
    healthcheck:
      test: "nc -vz rabbitmq 5672"
      interval: 1s
      timeout: 1s
      retries: 10
